exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

plugins:
  - jekyll-readme-index
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-youtube
  
permalink: /:title/
readme_index:
  enabled: true
  with_frontmatter: true

kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

github: [metadata]

# github:
#   private: false
#   license:
#     name: MIT
#   source:
#     branch: "main"
#     path: "/"
#   repository_url: "https://github.com/PiSaucer/tweakprimer"
  
title: Tweak Primer Theme
description: Tweak Primer is a Jekyll theme for GitHub Pages
