exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/PiSaucer/tweakprimer"
  
title: Tweak Primer Theme
description: Tweak Primer is a Jekyll theme for GitHub Pages
